create table if not exists payments (
     id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
     room_id BIGINT UNSIGNED NOT NULL,
     booking_id BIGINT UNSIGNED NOT NULL,
     proof VARCHAR(255) NOT NULL,

     FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE ON UPDATE CASCADE,
     FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE ON UPDATE CASCADE
)